[package]
name = "sol"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"

[lints.clippy]
complexity = "warn"
correctness = "warn"
nursery = "warn"
pedantic = "warn"
perf = "warn"
style = "warn"
suspicious = "warn"
